version: '3.6'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "USER123"
      POSTGRES_DB: "SIC"          
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
          
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4318:4318"   
      - "4317:4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
       ACCEPT_EULA: "Y"
    volumes:
      - ./seq-data:/data
        

volumes:
  dbdata6: